title = "Leaderboard"  # From Git
gitRepoUrl = "https://github.com/arxkdev/Leaderboard" # From Git

gitSourceBranch = "main"
changelog = true

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"
favicon = "/favicon.png"

# From git:
organizationName = "arxkdev"
projectName = "Leaderboard"
url = "https://arxkdev.github.io"
baseUrl = "/Leaderboard/"
tagline = "Global leaderboards with 5 lines of code."

[home]
enabled = true
includeReadme = true # Optional

[[home.features]]
title = "Simple"
description = "Leaderboard is so simple, you could have a Daily, Weekly and All Time leaderboard setup in 5 lines of code."
image = "/simple.png"

[[home.features]]
title = "Fast"
description = "Leaderboard is fast, it uses the latest and greatest of Roblox's API to ensure that it's as fast as possible."
image = "/hourglass.png"

[[home.features]]
title = "Lightweight"
description = "Leaderboard is a lightweight performance friendly library that is designed to be as lightweight as possible."
image = "/feather.png"

[[home.features]]

[[classOrder]]
section = "Leaderboard"
classes = ["Leaderboard", "Board", "MemoryShard"]

[[classOrder]]
section = "Util"
classes = ["Promise", "Signal", "Error"]

[footer]
style = "dark"
copyright = "Copyright © 2023 Arxk. Built with Moonwave and Docusaurus"